#!/bin/bash

# Store more than 9 variables...
i=1
for var in "$@"
do
    declare v${i}=$var
    ((i++))
done

touch ${v1}/${v2}".started"
if [[ "${v3}" == "True" ]]; then
      echo "DORIS PARALLEL:"
      echo "PYTHONPATH:"
      echo $PYTHONPATH
      echo ${v2}" "${v4}" "${v5}" "${v6}" "${v7}" "${v8}" "${v9}" "${v10}" "${v11}" "${v12}" "${v13}" "${v14}" "${v15}" started"
      date +%T
      pwd
      echo >> "./job.started"
fi
return_value=1
index=0
while [[ $return_value -ne 0 && index -le 5 ]]; do
    echo "INDEX = "$index
    if [[ $index -gt 0 ]]; then
        echo "DORIS PARALLEL Execution FAILED, retry nr "$index
        echo "DORIS PARALLEL "${v2}" "${v4}" "${v5}" "${v6}" "${v7}" "${v8}" "${v9}" "${v10}" "${v11}" "${v12}" "${v13}" "${v14}" "${v15}" RESTARTED"
    fi
    ${v4} ${v5} ${v6} ${v7} ${v8} ${v9} ${v10} ${v11} ${v12} ${v13} ${v14} ${v15} 2>&1 | tee job_$index_${v2}.log # start job
    return_value=$?
    if [ "${v3}" == "True" ]; then
        echo "DORIS PARALLEL return value is:"
        echo $return_value
    fi
    ((index++))
done
touch ${v1}/${v2}".finished"
if [ "${v3}" == "True" ]; then
      echo "DORIS PARALLEL:"
      echo ${v2}" "${v4}" "${v5}" "${v6}" "${v7}" "${v8}" "${v9}" "${v10}" "${v11}" "${v12}" "${v13}" "${v14}" "${v15}" finished"
      date +%T
      pwd
      echo >> "./job.finished"
fi



